services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal    # banco principal criado na inicialização
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 5s
      timeout: 5s
      retries: 12

  temporal:
    image: temporalio/auto-setup:1.28.1   # use auto-setup em dev
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgres
      - DBNAME=temporal
      - VISIBILITY_DBNAME=temporal_visibility
      - AUTO_SETUP=true                  # (na auto-setup é o padrão, mas ok manter)
      # opcional:
      # - NUM_HISTORY_SHARDS=512
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "7233:7233"

  temporal-ui:
    image: temporalio/ui:latest
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal
    ports:
      - "8233:8080"

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - TASK_QUEUE=my-task-queue
    depends_on:
      temporal:
        condition: service_started

  starter:
    build:
      context: .
      dockerfile: starter/Dockerfile
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - TASK_QUEUE=my-task-queue
    depends_on:
      worker:
        condition: service_started
    restart: "no"
